name: Update Data

on:
  schedule:
    # Update the project daily
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Test basic network connectivity
      run: curl -v https://www.auburn.edu
  
    - name: Test archive network connectivity
      run: curl -v https://ge-worker-apiproxy.sunlibo.workers.dev/

    - name: Run updateDataRevised.py
      run: python3 QGIS/data/updateDataRevised.py

    - name: Commit changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Updated Map Data"
          git push
        else
          echo "No changes to commit"
        fi
