name: Test Connection

on:
  workflow_dispatch:  # This allows manual trigger from GitHub Actions UI
    inputs:
      api_url:
        description: 'API URL to test'
        required: true
        default: 'https://georgeeliotarchive.org/api/collections'  # You can set a default value or change it during manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test API connection
      run: |
        echo "Testing connection to API: ${{ github.event.inputs.api_url }}"
        curl -v --retry 5 --retry-delay 5 --connect-timeout 30 "${{ github.event.inputs.api_url }}" || exit 1
